---

- name: Load the facts
  include_tasks: install/facts.yml

- name: Install the required packages
  include_tasks: install/packages.yml

- name: Format the storage
  include_tasks: install/format.yml

- name: Create and start the systemd storage
  include_tasks: install/systemd.yml

- name: Initialise the file systems
  include_tasks: install/init.yml
