---

- name: Install the parted utility
  apt:
    name: parted
    state: present

- name: Install the filesystem management packages
  when: storage_archive.fstype == 'btrfs'
  apt:
    name: btrfs-progs
    state: present
