---

- name: Create the first partition
  parted:
    device: '{{ storage_archive.device }}'
    number: 1
    label: gpt
    state: present

- name: Format the partition
  filesystem:
    device: '{{ storage_archive.device }}1'
    fstype: '{{ storage_archive.fstype }}'
    opts: '{{ storage_archive.mkfs_opts | join(" ") }}'

- name: Create the target directory if not already existing
  file:
    path: /home/archives
    state: directory
