---

storage:
  device: /dev/vdb
  live:
    fstype: btrfs
    mkfs_opts:
      - -R quota
      - --checksum xxhash
      - -L home-users
    mount_opts:
      - noatime
      - compress=lzo
  archives:
    fstype: btrfs
    mkfs_opts:
      - -R quota
      - --checksum xxhash
      - -L home-archives
    mount_opts:
      - noatime
      - compress=lzo
